### ISSUE TITLE
Contador de mortes

### ISSUE THREAD

**Issue by raphlmiranda** [thiagojobson/lutabra-war#2]
Poderia colocar contador de mortes no dia

**Comment by thiagojobson** [comment]
Olá, @raphlmiranda. Muito obrigado pela sugestão. 
Vou adicionar isso logo mais. 

Vlw

**Comment by thiagojobson** [comment]
@raphlmiranda, adicionei um score de mortes em cada dia.
Veja o que você achou.

**Comment by raphlmiranda** [comment]
@thiagojobson ficou muito bom.
