### ISSUE TITLE
Nomes com caracteres

### ISSUE THREAD

**Issue by raphlmiranda** [thiagojobson/lutabra-war#6]
Opá, mais uma vez importunando.

Poderia colocar os caracteres especiais nos nomes que possuem na deathlist.

Ex: Royal%27Riki
       Royal'Riki

**Comment by thiagojobson** [comment]
Opa, @raphlmiranda! Muito obrigado.
Acho que consegui resolver.

Pode continuar mandando issue, haha.
Abs.

**Comment by raphlmiranda** [comment]
Perfeito!
